# Generated by Django 5.2.6 on 2026-07-04 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('design', 'Design'), ('development', 'Development'), ('writing', 'Writing'), ('tutoring', 'Tutoring'), ('marketing', 'Marketing'), ('business_support', 'Business support'), ('home_repairs', 'Home repairs'), ('cleaning', 'Cleaning'), ('construction', 'Construction'), ('automotive', 'Automotive'), ('beauty_fashion', 'Beauty and fashion'), ('events', 'Events'), ('transport_errands', 'Transport and errands'), ('health_fitness', 'Health and fitness')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
