# Generated by Django 6.0.6 on 2026-07-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_profile_city_profile_latitude_profile_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
